version: 2

jobs:
  build:
    docker:
      - image: ${GOOGLE_DOCKER_REPOSITORY}/uber-builder:139
        auth: { username: _json_key, password: "${GOOGLE_CREDENTIALS}" }

    working_directory: ~/formistry

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build
          command: docker build -t formistry .

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: docker-tag-and-push formistry ${CIRCLE_BUILD_NUM}
