version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:112

    working_directory: ~/formistry

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build
          command: docker build -t formistry .

      - deploy:
          command: |
            # TODO - move all this to helper
            echo ${GCLOUD_SERVICE_KEY_BASE64} | base64 -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            rm ${HOME}/gcloud-service-key.json
            docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://eu.gcr.io

            docker tag formistry eu.gcr.io/quartic-global-c39fc822/formistry:${CIRCLE_BUILD_NUM}
            docker push eu.gcr.io/quartic-global-c39fc822/formistry:${CIRCLE_BUILD_NUM}
