version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:144

    working_directory: ~/formistry

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build
          command: docker build -t formistry .

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: docker-tag-and-push formistry ${CIRCLE_BUILD_NUM}
